//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY_HEADERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HISTORY_HEADERS()
        {
            this.HISTORY_LINES = new HashSet<HISTORY_LINES>();
        }
    
        public int HH_ID { get; set; }
        public string HH_PAYMENT_TYPE { get; set; }
        public Nullable<int> HH_TRANSACTION { get; set; }
        public System.DateTime HH_DATE { get; set; }
        public Nullable<int> HH_CUSTOMER { get; set; }
    
        public virtual TRANSACTIONS TRANSACTIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY_LINES> HISTORY_LINES { get; set; }
    }
}
