//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ITEMS()
        {
            this.HISTORY_LINES = new HashSet<HISTORY_LINES>();
            this.ORDER_LINES = new HashSet<ORDER_LINES>();
        }
    
        public int I_ID { get; set; }
        public string I_NAME { get; set; }
        public string I_SIZE { get; set; }
        public string I_DESCRIPTION { get; set; }
        public string I_CATEGORY { get; set; }
        public decimal I_PRICE { get; set; }
        public Nullable<int> I_IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY_LINES> HISTORY_LINES { get; set; }
        public virtual IMAGES IMAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_LINES> ORDER_LINES { get; set; }
    }
}
