//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PizzaServiceEntities : DbContext
    {
        public PizzaServiceEntities()
            : base("name=PizzaServiceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CUSTOMERS> CUSTOMERS { get; set; }
        public virtual DbSet<HISTORY_HEADERS> HISTORY_HEADERS { get; set; }
        public virtual DbSet<HISTORY_LINES> HISTORY_LINES { get; set; }
        public virtual DbSet<IMAGES> IMAGES { get; set; }
        public virtual DbSet<ITEMS> ITEMS { get; set; }
        public virtual DbSet<ORDER_HEADERS> ORDER_HEADERS { get; set; }
        public virtual DbSet<ORDER_LINES> ORDER_LINES { get; set; }
        public virtual DbSet<STORES> STORES { get; set; }
        public virtual DbSet<TRANSACTIONS> TRANSACTIONS { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<REVIEWS> REVIEWS { get; set; }
    }
}
