//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_HEADERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER_HEADERS()
        {
            this.ORDER_LINES = new HashSet<ORDER_LINES>();
        }
    
        public int OH_ID { get; set; }
        public string OH_ADDRESS { get; set; }
        public int OH_CUSTOMER { get; set; }
        public int OH_STORE { get; set; }
        public System.DateTime OH_DATE { get; set; }
        public Nullable<double> OH_SUM { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
        public virtual STORES STORES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_LINES> ORDER_LINES { get; set; }
    }
}
