//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_LINES
    {
        public int OL_ID { get; set; }
        public Nullable<int> OL_ORDER_HEADER { get; set; }
        public int OL_ITEM { get; set; }
        public int OL_QUANTITY { get; set; }
    
        public virtual ITEMS ITEMS { get; set; }
        public virtual ORDER_HEADERS ORDER_HEADERS { get; set; }
    }
}
