//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PizzaServiceDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEWS
    {
        public int R_ID { get; set; }
        public string R_TEXT { get; set; }
        public System.DateTime R_DATE { get; set; }
        public int R_CUSTOMERID { get; set; }
    
        public virtual CUSTOMERS CUSTOMERS { get; set; }
    }
}
