//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsersDataEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public int U_ID { get; set; }
        public int U_LOGIN { get; set; }
        public int U_PASSWORD { get; set; }
        public string U_MODIFIER { get; set; }
    }
}
